"""initial

Revision ID: b00c8b315bae
Revises: 
Create Date: 2026-06-14 08:56:12.028063

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b00c8b315bae'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('instance', sa.String(), nullable=False),
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_uuid', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_report', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_items_identity'), 'change_items', ['identity'], unique=True)
    op.create_index(op.f('ix_change_items_status'), 'change_items', ['status'], unique=False)
    op.create_table('window_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('considered', sa.Integer(), nullable=False),
    sa.Column('applied', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('window_run_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('rollback', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['change_items.id'], ),
    sa.ForeignKeyConstraint(['window_run_id'], ['window_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('window_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['change_attempts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['change_items.id'], ),
    sa.ForeignKeyConstraint(['window_run_id'], ['window_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_item_id'), 'change_events', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_events_item_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_table('change_attempts')
    op.drop_table('window_runs')
    op.drop_index(op.f('ix_change_items_status'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_identity'), table_name='change_items')
    op.drop_table('change_items')
    # ### end Alembic commands ###
